### ISSUE TITLE
Update checkout action to use Node v20

### ISSUE THREAD

**Issue by ja573** [tarides/changelog-check-action#4]
Currently relying on actions/checkout@v3 that depends on node v16, which is deprecated

**Comment by smorimoto** [comment]
@Leonidas-from-XIV We should update the v2 tag. Here is a way to do that: https://github.com/ocaml/setup-ocaml/blob/master/scripts/release.sh

**Comment by Leonidas-from-XIV** [comment]
Last time I did an update of checkout I bumped from `v2` to `v3`, maybe that's a better solution?

**Comment by smorimoto** [comment]
It's a good practice to bump the release of this action from v2 to v3, or just move the v2 tag. In many cases, updating the `actions/checkout` version can only break legacy GitHub Enterprise environments.

**Comment by smorimoto** [comment]
Upstream (actions team) major version bump is due to the action runtime update, but in most cases that's a minor issue. In setup-ocaml, runtime updates are considered to be non-breaking changes 🙃

**Comment by Leonidas-from-XIV** [comment]
I've created `v3` just to be careful and for consistency with how this was done before, but yeah, it *probably* would've been fine.
