### ISSUE TITLE
Needs a new commit after adding "no changelog" label

### ISSUE THREAD

**Issue by Patabugen** [tarides/changelog-check-action#6]
I'm using this handy action on a project, and just had my first need to use the `no changelog` label (thanks for the amazingly helpful output that explains that's what to to, by the way!).

I found that I needed to push a new commit to the PR after adding the label for it to be picked up.

I wanted to raise it in case there's anything you're able to do to avoid that, but also in case anyone else comes across this problem - hopefully this ticket can save them a few minutes.

**Comment by Leonidas-from-XIV** [comment]
Normally this doesn't seem to be the case in the projects I've applied it to (I currently don't have a case from the top of my head that I could link here as an example), setting the tag usually re-triggers the action.

I agree that this is annoying to push pointless commits to have CI be happy, maybe your project has some kind of "no rerun on label change" setting? Or it recently changed on the Github side?

**Comment by Patabugen** [comment]
ooh strange, I know GitHub does occasionally miss re-runs now and then - so this could be a fluke case like that.

We wouldn't have set a setting like a "no rerun on label change" I don't think.

I've only tried to use the "no changelog" label once on one PR, so something else could have gone wrong.

I'll remember this, and if/when I need to use it again I'll keep an eye out!

**Comment by Leonidas-from-XIV** [comment]
Thanks! If you find out something about it let me know, I'll try to fix it if possible.

**Comment by Leonidas-from-XIV** [comment]
Feel free to reopen if this happens but it's been working pretty reliably for me.
